-- Add up migration script here
INSERT INTO players
  (id, name)
VALUES
  (1, 'Tait Hoyem'),
  (2, 'Hillary Scanlon'),
  (3, 'Nelson Rego'),
  (4, 'Carrie Anton'),
  (5, 'Salamaan Chaudhri'),
  (6, 'Ben Ho Lung'),
  (7, 'Brian MacLean'),
  (8, 'Shannon Murphy'),
  (9, 'Joseph Robinson'),
  (10, 'Drexcyl Sison'),
  (11, 'Ginny Sweet'),
  (12, 'Catharine Lemay'),
  (13, 'Thomas Stewart'),
  (14, 'Maurice Clement-Lafrance'),
  (15, 'Jennifer Fancy'),
  (16, 'Allyssa Foulds'),
  (17, 'Ryan Kucy'),
  (18, 'Denis LeBlanc'),
  (19, 'Bob Lowe'),
  (20, 'Ted Moritsugu'),
  (21, 'Dave Poidevin'),
  (22, 'Jillian Stewart'),
  (23, 'Laura Mark'),
  (24, 'Matt Arnold'),
  (25, 'Rory Kucy'),
  (26, 'Jeff Stewart'),
  (27, 'Dylan Brown'),
  (28, 'Codi Isaac'),
  (29, 'Richard Isaac'),
  (30, 'Tyler McGuffin'),
  (31, 'Scarlette Dorn');
